### ISSUE TITLE
Missing lang string on roles page - pixabay:view

### ISSUE THREAD

**Issue by kristian-94** [yedidiaklein/moodle-repository_pixabay#10]
If you go to the editing roles page with the repo enabled, Site administration -> Users -> Permissions -> Define roles 

eg. http://moodle.local/admin/roles/define.php?action=edit&roleid=2

you will get a lang string error

> Invalid get_string() identifier: 'pixabay:view' or component 'repository_pixabay'. Perhaps you are missing $string['pixabay:view'] = ''; in /var/www/site/repository/pixabay/lang/en/repository_pixabay.php?
> 
>     line 353 of /lib/classes/string_manager_standard.php: call to debugging()
>     line 7309 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
>     line 2667 of /lib/accesslib.php: call to get_string()
>     line 2512 of /lib/accesslib.php: call to get_capability_string()
>     line 118 of /admin/roles/classes/capability_table_base.php: call to get_capability_docs_link()
>     line 135 of /admin/roles/classes/capability_table_with_risks.php: call to core_role_capability_table_base->display()
>     line 678 of /admin/roles/classes/define_role_table_advanced.php: call to core_role_capability_table_with_risks->display()
>     line 268 of /admin/roles/define.php: call to core_role_define_role_table_advanced->display()

**Comment by yedidiaklein** [comment]
Merged, tnx!
