### ISSUE TITLE
Consider using Moodle CURL (to support PROXY)

### ISSUE THREAD

**Issue by nadavkav** [yedidiaklein/moodle-repository_pixabay#12]
We are blocked when trying to use this plugin from within our institute as all outside communication is directed via a reverse proxy.

Please consider changing file_get_content()
https://github.com/yedidiaklein/moodle-repository_pixabay/blob/master/lib.php#L81
Into Moodle's CURL that supports PROXY admin settings.

Here is a quick suggestion (that helped us workaround this issue)
        //$json = file_get_contents($url);
        $curl = new curl();
        $json = $curl->get($url);

**Comment by yedidiaklein** [comment]
Hi nadav, tnx!
is you patch working well ?

Do you want to fork and "pull request" ?

**Comment by nadavkav** [comment]
Yes. seem to work well for quite some time now.

**Comment by nadavkav** [comment]
Added pull request #13

**Comment by yedidiaklein** [comment]
tnx, merged
