### ISSUE TITLE
Inconsistency in getting the configured API key

### ISSUE THREAD

**Issue by mudrd8mz** [yedidiaklein/moodle-repository_pixabay#2]
There are both
```
$key = get_config('pixabay', 'key');
```
and
```
$key = get_config('repository_pixabay', 'key');
```
Is there a reason for the later one? My understanding is that repositories store their config under the name without the repository prefix. I am aware this has been badly designed but that is what we have. As far as I can tell, there is no config value stored under "repository_pixabay" plugin.

**Comment by yedidiaklein** [comment]
I fixed it for consistency, I still do not understand how did it worked on the  setting form.
