### ISSUE TITLE
repository only showing for admins

### ISSUE THREAD

**Issue by krajewsk** [yedidiaklein/moodle-repository_pixabay#7]
We just installed it to try it out and are finding only admins can see it. Students and instructors cannot.  Authenticated user has the permission as is assigned by default.  We're Moodle 3.6.5+ (Build: 20190816).  Any ideas?

**Comment by yedidiaklein** [comment]
Hi,

I just installed a fresh version of moodle3.6 (2018120308.00) and tested the repo as teacher. and it works well.

0. I assume that you enabled it and got a api key fro pixabay.
1. how did you try to use it ? from atto ?
2. could you purge the server cache and try again ?
3. any chance to upgrade to latest 3.6 ?
4. could you try  install a clean 3.6 on this server or similar server.

tnx, 
--Yedidia

**Comment by krajewsk** [comment]
Thanks Yedidia for the helpful questions.
0. Correct. It worked fine for admins.
1. TinyMCE is our default editor.
2. Done.
3. We can't upgrade our production to a newer 3.6 as classes are in session.  We don't make those changes during a semester.
4. We'll have a new server this summer (running latest version) for next school year so it might have to wait until then.

I just tried deleting it and re-installing it from github and now no one sees it - even admins.  So I'm going to let it sit for a bit and see if it cures itself.

**Comment by yedidiaklein** [comment]
couldn't reproduce...
